version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  url-shortener-server:
    container_name: url-shortener-server
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    build:
      context: ./
    image: url-shortener-server
    ports:
    - "8080:8080"
